services:
  - type: web
    name: email-generator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENROUTER_API_KEY
        value: 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  # use real key or leave blank if using dashboard
      - key: SENDER_EMAIL
        value: aajay21001@iiitd.ac.in
      - key: SENDER_PASSWORD
        value: ymzq eqmi bxfv qycu
